name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          check-latest: true
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
          
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk
      
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
        
